export const adminImages = [
    {image:"", fullName: "Keilan Almonte", Title: "Pastor"},
    {image:"", fullName: "Radaiza Almonte", Title: "Pastora"},
    {image:"", fullName: "Victoria Estrella", Title: "Tesorera"},
    {image:"https://i.imgur.com/culx4Kh.jpg", fullName: "Angelines YaportGarcia", Title: "Secretaria"},
    {image:"", fullName: "Miriam Alvarez", Title: "Anciana"},
    {image:"", fullName: "Maria Mercedes", Title: "Anciana"},
    {image:"", fullName: "Vicenta Lora (Mery)", Title: "Anciana"},
    {image:"", fullName: "Marilyn Ramirez", Title: "Anciana"},
    {image:"", fullName: "Ramon Mendez", Title: "Anciano"},
]
export const albanzImages = [
    {image:"", fullName: "Luz Nunez (Chili)", Title: "Lider de Alabanza y Adoracion"},
    {image:"", fullName: "Hether Almonte", Title: "Directora de Musica"},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
]
export const jovenesImages = [
    {image:"", fullName: "Jose Vargas", Title: "Pastor de Jovenes"}, 
    {image:"", fullName: "Charlenny Vargas", Title: "Pastora de Jovenes"},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},   
]
export const danzaImages = [
    {image:"", fullName: "Angelines YaportGarcia", Title: "Supervisora de Danza"}, 
    {image:"", fullName: "Kelly Estrella", Title: "Lider de Danza"},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""}, 
]
export const danceImages = [
    {image:"", fullName: "Manyely Garcia", Title: "Lider de Danza"}, 
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
]
export const evangImages = [
    {image:"", fullName: "", Title: ""}, 
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
]
export const intercImages = [
    {image:"", fullName: "", Title: ""}, 
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
]
export const ujiereImages = [
    {image:"", fullName: "", Title: ""}, 
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
]
// export const adminImages = [
//     {image:"", fullName: "", Title: ""},
//     {image:"", fullName: "", Title: ""},
//     {image:"", fullName: "", Title: ""},
// // ]