export const adminImages = [
    {image:"", fullName: "Keilan Almonte", Title: "Pastor"},
    {image:"", fullName: "Radaiza Almonte", Title: "Pastora"},
    {image:"", fullName: "Victoria Estrella", Title: "Tesorera"},
    {image:"", fullName: "Angelines YaportGarcia", Title: "Secretaria"},
    {image:"", fullName: "Miriam Alvarez", Title: "Anciana"},
    {image:"", fullName: "Maria Mercedes", Title: "Anciana"},
    {image:"", fullName: "Vicenta Lora (Mery)", Title: "Anciana"},
    {image:"", fullName: "Marilyn Ramirez", Title: "Anciana"},
    {image:"", fullName: "Ramon Mendez", Title: "Anciano"},
]
export const albanzImages = [
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
]
export const jovenesImages = [
    {image:"", fullName: "", Title: ""}, 
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},   
]
export const danzaImages = [
    {image:"", fullName: "", Title: ""}, 
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""}, 
]
export const danceImages = [
    {image:"", fullName: "", Title: ""}, 
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
]
export const evangImages = [
    {image:"", fullName: "", Title: ""}, 
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
]
export const intercImages = [
    {image:"", fullName: "", Title: ""}, 
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
]
export const ujiereImages = [
    {image:"", fullName: "", Title: ""}, 
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
    {image:"", fullName: "", Title: ""},
]
// export const adminImages = [
//     {image:"", fullName: "", Title: ""},
//     {image:"", fullName: "", Title: ""},
//     {image:"", fullName: "", Title: ""},
// // ]